import { create } from "zustand";

const useStoreProducts = create((set) => ({
    products:[
    {
        "id": 1,
        "name": "Blue T-Shirt",
        "price": 24000,
        "category": "Tops",
        "subcategory" : "T-Shirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This T-shirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/86/ff/c6/86ffc66938801433d3e2b1a166e272e4.jpg",
    },
    {
        "id": 2,
        "name": "White T-Shirt",
        "price": 23400,
        "category": "Tops",
        "subcategory" : "T-Shirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This T-shirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/7f/25/e5/7f25e5ef865c2a5b77b43eaf0ac7dcbc.jpg",
    },
    {
        "id": 3,
        "name": "Olive T-Shirt",
        "price": 25000,
        "category": "Tops",
        "subcategory" : "T-Shirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This T-shirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/61/17/4a/61174a4eaffb58ec4a7ffbf553271056.jpg",
    },
    {
        "id": 4,
        "name": "Stripe Zip T-Shirt",
        "price": 26000,
        "category": "Tops",
        "subcategory" : "T-Shirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This T-shirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/72/a0/8a/72a08a8188ad60f2a925fb6ca16fa9de.jpg",
    },
    {
        "id": 5,
        "name": "Creamy T-Shirt",
        "price": 25500,
        "category": "Tops",
        "subcategory" : "T-Shirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This T-shirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/32/de/a8/32dea81c032c7e8e5d858b7cd1ea5639.jpg",
    },
    {
        "id": 6,
        "name": "Peach V-Blouse",
        "price": 24000,
        "category": "Tops",
        "subcategory" : "Blouses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Blouses is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://i.pinimg.com/474x/9e/27/29/9e27294f8c78eb30398b10fc1709f5a7.jpg",
    },
    {
        "id": 7,
        "name": "White Blouse",
        "price": 21500,
        "category": "Tops",
        "subcategory" : "Blouses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Blouses is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/87/883/M_p0150288387.jpg",
    },
    {
        "id": 8,
        "name": "Flowal White Blouse",
        "price": 18000,
        "category": "Tops",
        "subcategory" : "Blouses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Blouses is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/72/200/M_p0170520072.jpg",
    },
    {
        "id": 9,
        "name": "Broney Blouse",
        "price": 20000,
        "category": "Tops",
        "subcategory" : "Blouses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Blouses is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/84/208/M_p0193320884.jpg",
    },
    {
        "id": 10,
        "name": "Blue Blouse",
        "price": 16000,
        "category": "Tops",
        "subcategory" : "Blouses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Blouses is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/27/016/M_p0210701627.jpg",
    },
    {
        "id": 11,
        "name": "Black Sweater",
        "price": 29900,
        "category": "Tops",
        "subcategory" : "Sweaters",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Sweater is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/83/605/M_p0188260583.jpg",
    },
    {
        "id": 12,
        "name": "Striped Sweater",
        "price": 27000,
        "category": "Tops",
        "subcategory" : "Sweaters",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Sweater is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/58/233/M_p0180323358.jpg",
    },
    {
        "id": 13,
        "name": "Broney Sweater",
        "price": 15000,
        "category": "Tops",
        "subcategory" : "Sweaters",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Sweater is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/90/538/M_p0188853890.jpg",
    },
    {
        "id": 14,
        "name": "Gray Sweater",
        "price": 21000,
        "category": "Tops",
        "subcategory" : "Sweaters",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Sweater is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/13/077/M_p0212007713.jpg",
    },
    {
        "id": 15,
        "name": "Classic Sweater",
        "price": 24000,
        "category": "Tops",
        "subcategory" : "Sweaters",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Sweater is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/95/390/M_p0184739095.jpg",
    },
    {
        "id": 16,
        "name": "Skinny Bell Jean",
        "price": 32000,
        "category": "Bottoms",
        "subcategory" : "Jeans",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Jean is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/04/598/M_p0139159804.jpg",
    },
    {
        "id": 17,
        "name": "Sora Blue Jean",
        "price": 35000,
        "category": "Bottoms",
        "subcategory" : "Jeans",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Jean is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/36/973/M_p0208997336.jpg",
    },
    {
        "id": 18,
        "name": "Classic Blue Jean",
        "price": 31000,
        "category": "Bottoms",
        "subcategory" : "Jeans",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Jean is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/17/894/M_p0116289417.jpg",
    },
    {
        "id": 19,
        "name": "Kawai Blue Jean",
        "price": 37000,
        "category": "Bottoms",
        "subcategory" : "Jeans",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Jean is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/43/355/M_p0177535543.jpg",
    },
    {
        "id": 20,
        "name": "Blacked Jean",
        "price": 24000,
        "category": "Bottoms",
        "subcategory" : "Jeans",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This Jean is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/81/702/M_p0189570281.jpg",
    },
    {
        "id": 21,
        "name": "Dreamy Skirt",
        "price": 15000,
        "category": "Bottoms",
        "subcategory" : "Skirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This skirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/65/346/M_p0206834665.jpg",
    },
    {
        "id": 22,
        "name": "Sweet Skirt",
        "price": 20000,
        "category": "Bottoms",
        "subcategory" : "Skirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This skirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/74/980/M_p0134098074.jpg",
    },
    {
        "id": 23,
        "name": "Pinky Skirt",
        "price": 21900,
        "category": "Bottoms",
        "subcategory" : "Skirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This skirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/48/011/M_p0208201148.jpg",
    },
    {
        "id": 24,
        "name": "Mini Jean Skirt",
        "price": 27000,
        "category": "Bottoms",
        "subcategory" : "Skirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This skirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/93/493/M_p0205949393.jpg",
    },
    {
        "id": 25,
        "name": "Playful Jean Skirt",
        "price": 26000,
        "category": "Bottoms",
        "subcategory" : "Skirts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This skirt is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/73/294/M_p0208129473.jpg",
    },
    {
        "id": 26,
        "name": "Joyful Short",
        "price": 23000,
        "category": "Bottoms",
        "subcategory" : "Shorts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This short is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/36/786/M_p0209778636.jpg",
    },
    {
        "id": 27,
        "name": "Happy Short",
        "price": 22000,
        "category": "Bottoms",
        "subcategory" : "Shorts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This short is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/33/929/M_p0206992933.jpg",
    },
    {
        "id": 28,
        "name": "Breezy Short",
        "price": 25000,
        "category": "Bottoms",
        "subcategory" : "Shorts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This short is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/72/749/M_p0170374972.jpg",
    },
    {
        "id": 29,
        "name": "Classic Short",
        "price": 18500,
        "category": "Bottoms",
        "subcategory" : "Shorts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This short is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/09/696/M_p0210969609.jpg",
    },
    {
        "id": 30,
        "name": "Classic Black Short",
        "price": 20000,
        "category": "Bottoms",
        "subcategory" : "Shorts",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This short is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/32/635/M_p0130563532.jpg",
    },
    {
        "id": 31,
        "name": "Cutie Dress",
        "price": 24000,
        "category": "Dresses",
        "subcategory" : "Short Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/96/315/M_p0127231596.jpg",
    },
    {
        "id": 32,
        "name": "Whtie Short Dress",
        "price": 26000,
        "category": "Dresses",
        "subcategory" : "Short Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/36/595/M_p0207459536.jpg",
    },
    {
        "id": 33,
        "name": "Classic Short Dress",
        "price": 21000,
        "category": "Dresses",
        "subcategory" : "Short Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/05/784/M_p0178078405.jpg",
    },
    {
        "id": 34,
        "name": "Cutie Short Dress",
        "price": 23000,
        "category": "Dresses",
        "subcategory" : "Short Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/30/870/M_p0154387030.jpg",
    },
    {
        "id": 35,
        "name": "Princess Short Dress",
        "price": 28000,
        "category": "Dresses",
        "subcategory" : "Short Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/46/654/M_p0193365446.jpg",
    },
    {
        "id": 36,
        "name": "Classic Long Dress",
        "price": 24000,
        "category": "Dresses",
        "subcategory" : "Long Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/50/068/M_p0136006850.jpg",
    },
    {
        "id": 37,
        "name": "Flowal Long Dress",
        "price": 28000,
        "category": "Dresses",
        "subcategory" : "Long Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/94/370/M_p0198937094.jpg",
    },
    {
        "id": 38,
        "name": "Blue Long Dress",
        "price": 26000,
        "category": "Dresses",
        "subcategory" : "Long Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/88/459/M_p0212045988.jpg",
    },
    {
        "id": 39,
        "name": "Office Long Dress",
        "price": 23500,
        "category": "Dresses",
        "subcategory" : "Long Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/61/818/M_p0212081861.jpg",
    },
    {
        "id": 40,
        "name": "Baby Long Dress",
        "price": 19000,
        "category": "Dresses",
        "subcategory" : "Long Dresses",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This dress is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/19/588/M_p0212158819.jpg",
    },
    {
        "id": 41,
        "name": "Butterfly OutWear",
        "price": 14000,
        "category": "Other",
        "subcategory" : "Outer Wears",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This outwear is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/25/445/M_p0179244525.jpg",
    },
    {
        "id": 42,
        "name": "Office OutWear",
        "price": 16000,
        "category": "Other",
        "subcategory" : "Outer Wears",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This outwear is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/90/423/M_p0198142390.jpg",
    },
    {
        "id": 43,
        "name": "Classic Hoddie",
        "price": 18000,
        "category": "Other",
        "subcategory" : "Hoodies",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This hoddie is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/78/179/M_p0136717978.jpg",
    },
    {
        "id": 44,
        "name": "StawBerry Pajamas",
        "price": 15000,
        "category": "Other",
        "subcategory" : "Pajamas",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This pajamas is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/85/105/M_p0123410585.jpg",
    },
    {
        "id": 45,
        "name": "White Pajamas",
        "price": 16000,
        "category": "Other",
        "subcategory" : "Pajamas",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This pajamas is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/18/383/M_p0184238318.jpg",
    },
    {
        "id": 46,
        "name": "Classic Pajamas",
        "price": 15500,
        "category": "Other",
        "subcategory" : "Pajamas",
        "size" : ["S", "M", "L", "XL"],
        "description" : "This pajamas is incredibly comfortable to wear, making it a perfect choice for any occasion. Its versatile design is ideal for all seasons—keeping you cool during hot summer days and providing just the right amount of warmth in winter. With its trendy style, it’s a favorite among the youth, allowing you to effortlessly pair it with any outfit. Whether you're heading out for a casual day or a night out, this shirt will ensure you look stylish and eye-catching wherever you go.",
        "image" : "https://d1flfk77wl2xk4.cloudfront.net/Assets/68/651/M_p0192065168.jpg",
    },
]
}))

export default useStoreProducts;